apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana-operator
  template:
    metadata:
      labels:
        name: grafana-operator
        razee/watch-resource: "detail"
    spec:
      serviceAccountName: grafana-operator
      containers:
        - name: grafana-operator
          image: cp.stg.icr.io/cp/om/grafana-operator:latest
          args:
            - '--grafana-image=cp.stg.icr.io/cp/om/origin-grafana'
            - '--grafana-image-tag=latest'
            - '--grafana-plugins-init-container-image=cp.stg.icr.io/cp/om/origin-grafana'
            - '--grafana-plugins-init-container-tag=0.0.2'
            - '--image-pull-secret=entitled-registry'
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - grafana-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: TEMPLATE_PATH
              value: /usr/local/bin/templates
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "grafana-operator"