apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    razee/watch-resource: "lite"
    tag: razee-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      razee/watch-resource: "lite"
  template:
    metadata:
      labels:
        app: nginx
        razee/watch-resource: "lite"
        tag: razee-nginx
    spec:
      containers:
        - name: front-end
          image: nginx
          ports:
            - containerPort: 80
