apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    razee/watch-resource: "debug"
    app: nginx
    tag: help
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        razee/watch-resource: "debug"
        tag: help
    spec:
      containers:
        - name: front-end
          image: nginx
          ports:
            - containerPort: 80
