apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudnew
  template:
    metadata:
      name: one
      labels:
        app: cloudnew
        razee/watch-resource: "detail"
    spec:
      containers:
      - name: one
        image: redis
