apiVersion: v1
kind: List
metadata:
  name: liberty-service
type: array
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: release-name-ibm-websphe
      labels:
        chart: "ibm-websphere-liberty-1.10.0"
        app: release-name-ibm-websphe
        release: "release-name"
        heritage: "Tiller"
    spec:  
      type: NodePort
      ports:
      - port: 9443
        targetPort: 9443
        protocol: TCP
        name: "https"
      selector:
        app: release-name-ibm-websphe