apiVersion: v1
kind: List
metadata:
  name: liberty-deployment
type: array
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: release-name-ibm-websphe
      labels:
        chart: "ibm-websphere-liberty-1.10.0"
        app: release-name-ibm-websphe
        release: "release-name"
        heritage: "Tiller"
    imagePullSecrets:
      - name: sa-default