apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 name: redhat-marketplace-operator
 namespace: openshift-operators
spec:
 channel: alpha
 installPlanApproval: Automatic
 name: redhat-marketplace-operator
 source: rhm-configmap-catalog-source
 sourceNamespace: openshift-marketplace
 startingCSV: redhat-marketplace-operator.v0.0.1
